sudo: required

language: c

services:
  - docker

env:
  - TEST_SUITE=gnat-community-2018

git:
  submodules: false

before_install:
  - git submodule update --init --recursive --depth=1

script:
  - if [ "$TEST_SUITE" = "gnat-community-2018" ]; then docker run -v $PWD:/app -w /app jklmnn/gnat:gpl.2018.slim /bin/sh -c "apt-get update && apt-get install -y --no-install-recommends ca-certificates libssl1.1 libssl-dev git && make NO_SPARK=1 CC=gcc tests"; fi
